// apps/users-portal-vue/src/app/error-boundary/error-boundary.vue
<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue';

// Vue's equivalent of React's ErrorBoundary class component: onErrorCaptured
// catches errors thrown by descendants during render/lifecycle.
const error = ref<Error | null>(null);

onErrorCaptured((err) => {
  error.value = err instanceof Error ? err : new Error(String(err));
  console.error('[ErrorBoundary]', error.value);
  return false; // stop the error from propagating further
});
</script>

<template>
  <slot v-if="!error" />
  <slot v-else name="fallback" :error="error">
    <div class="container">
      <h2 class="heading">Something went wrong</h2>
      <pre class="message">{{ error.message }}</pre>
    </div>
  </slot>
</template>

<style scoped>
.container {
  max-width: 600px;
  margin: 2rem auto;
  padding: 1.5rem;
  border: 1px solid #fca5a5;
  border-radius: 8px;
  background: #fef2f2;
  color: #dc2626;
}
.heading {
  margin: 0 0 0.5rem;
}
.message {
  margin: 0;
  font-size: 0.875rem;
  white-space: pre-wrap;
  word-break: break-word;
}
</style>

// libs/users-react/ui/src/lib/error-boundary/error-boundary.tsx
import { Component, CSSProperties, ReactNode } from 'react';

interface Props {
  children: ReactNode;
  fallback?: ReactNode;
}

interface State {
  error: Error | null;
}

export class ErrorBoundary extends Component<Props, State> {
  state: State = { error: null };

  static getDerivedStateFromError(error: Error): State {
    return { error };
  }

  componentDidCatch(error: Error, info: { componentStack: string }) {
    console.error('[ErrorBoundary]', error, info.componentStack);
  }

  render() {
    if (this.state.error) {
      return this.props.fallback ?? <DefaultFallback error={this.state.error} />;
    }
    return this.props.children;
  }
}

function DefaultFallback({ error }: { error: Error }) {
  return (
    <div style={containerStyle}>
      <h2 style={{ margin: '0 0 0.5rem' }}>Something went wrong</h2>
      <pre style={messageStyle}>{error.message}</pre>
    </div>
  );
}

const containerStyle: CSSProperties = {
  maxWidth: 600,
  margin: '2rem auto',
  padding: '1.5rem',
  border: '1px solid #fca5a5',
  borderRadius: 8,
  background: '#fef2f2',
  color: '#dc2626',
};

const messageStyle: CSSProperties = {
  margin: 0,
  fontSize: '0.875rem',
  whiteSpace: 'pre-wrap',
  wordBreak: 'break-word',
};
