// libs/users-react/feature/src/lib/user-orders/user-orders.tsx
import type { CSSProperties } from 'react';
import { useUsersFacade } from '../use-users-facade';
import { UserButtons, UserName, UserTotalOrders, OrdersCard, ToastStack } from '@portal/users-react/ui';
import styles from './user-orders.module.css';

export function UserOrders() {
  const { users, loading, loaded, error, selectedUserId, selectedUserSummary, orders, selectUser, notifications, dismissOrderNotification } =
    useUsersFacade();

  return (
    <>
    <ToastStack notifications={notifications} onDismiss={dismissOrderNotification} />
    <section style={shellStyle}>
      <header style={pageHeaderStyle}>
        <h1 style={{ margin: '0 0 0.5rem' }}>Users orders dashboard</h1>
        <div style={subtitleRowStyle}>
          <p style={{ margin: 0, color: '#667085' }}>Facade-driven example with TanStack Query and React.</p>
          <span className={`${styles.spinner} ${loading ? '' : styles.hidden}`} aria-label="Loading" />
        </div>
      </header>

      {error && <p style={errorStyle}>{error}</p>}

      <UserButtons users={users} selectedUserId={selectedUserId} onSelect={selectUser} />

      {selectedUserSummary ? (
        <>
          <div style={summaryGridStyle}>
            <UserName userName={selectedUserSummary.userName} />
            <UserTotalOrders totalAmount={selectedUserSummary.totalAmount} />
          </div>
          <OrdersCard orders={orders} loading={ordersLoading(loading, selectedUserId)} loaded={loaded} error={error} />
        </>
      ) : !loading && loaded ? (
        <p style={emptyStateStyle}>Select a user</p>
      ) : null}
    </section>
    </>
  );
}

function ordersLoading(globalLoading: boolean, selectedUserId: number | null): boolean {
  return globalLoading && selectedUserId !== null;
}

// ─── Styles ──────────────────────────────────────────────────────────────────

const shellStyle: CSSProperties = { maxWidth: 900, margin: '0 auto', padding: '2rem' };
const pageHeaderStyle: CSSProperties = { marginBottom: '1.5rem' };
const subtitleRowStyle: CSSProperties = { display: 'flex', alignItems: 'center', gap: 8 };
const summaryGridStyle: CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  gap: '1rem',
  marginBottom: '1.5rem',
};
const errorStyle: CSSProperties = { color: '#dc2626' };
const emptyStateStyle: CSSProperties = { padding: '1rem', color: '#667085' };

// libs/users-vue/feature/src/lib/user-orders/UserOrders.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useUsersFacade } from '../use-users-facade';
import {
  UserButtons,
  UserName,
  UserTotalOrders,
  OrdersCard,
  ToastStack,
} from '@portal/users-vue/ui';

// Smart container: calls the facade and lays out the dumb ui components.
// Destructuring is safe — every field is a ComputedRef, so it stays reactive.
const {
  users,
  loading,
  loaded,
  error,
  selectedUserId,
  selectedUserSummary,
  orders,
  notifications,
  selectUser,
  dismissOrderNotification,
} = useUsersFacade();

const ordersLoading = computed(() => loading.value && selectedUserId.value !== null);
</script>

<template>
  <ToastStack :notifications="notifications" @dismiss="dismissOrderNotification" />

  <section class="shell">
    <header class="page-header">
      <h1 class="title">Users orders dashboard</h1>
      <div class="subtitle-row">
        <p class="subtitle">Facade-driven example with TanStack Query and Vue.</p>
        <span class="spinner" :class="{ hidden: !loading }" aria-label="Loading" />
      </div>
    </header>

    <p v-if="error" class="error">{{ error }}</p>

    <UserButtons :users="users" :selected-user-id="selectedUserId" @select="selectUser" />

    <template v-if="selectedUserSummary">
      <div class="summary-grid">
        <UserName :user-name="selectedUserSummary.userName" />
        <UserTotalOrders :total-amount="selectedUserSummary.totalAmount" />
      </div>
      <OrdersCard :orders="orders" :loading="ordersLoading" :loaded="loaded" :error="error" />
    </template>
    <p v-else-if="!loading && loaded" class="empty">Select a user</p>
  </section>
</template>

<style scoped>
.shell {
  max-width: 900px;
  margin: 0 auto;
  padding: 2rem;
}
.page-header {
  margin-bottom: 1.5rem;
}
.title {
  margin: 0 0 0.5rem;
}
.subtitle-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
.subtitle {
  margin: 0;
  color: #667085;
}
.summary-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 1rem;
  margin-bottom: 1.5rem;
}
.error {
  color: #dc2626;
}
.empty {
  padding: 1rem;
  color: #667085;
}
.spinner {
  width: 16px;
  height: 16px;
  border: 2px solid #cbd5e1;
  border-top-color: #0f172a;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}
.spinner.hidden {
  visibility: hidden;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
