// apps/users-portal-vue/src/app/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import { useOrdersStream } from '@portal/users-vue/data-access';
import { ErrorBoundary } from '@portal/users-vue/ui';

// Infrastructure side-effect — opened once at the app root (the WebSocket
// singleton), never inside a route-bound component.
useOrdersStream();
</script>

<template>
  <ErrorBoundary>
    <RouterView />
  </ErrorBoundary>
</template>

// apps/users-portal-react/src/app/app.tsx
import { Navigate, Route, Routes } from 'react-router-dom';
import { UserOrders } from '@portal/users-react/feature';
import { useOrdersStream } from '@portal/users-react/data-access';
import { ErrorBoundary } from '@portal/users-react/ui';

export function App() {
  useOrdersStream();
  return (
    <ErrorBoundary>
      <Routes>
        <Route path="/users/:userId" element={<UserOrders />} />
        <Route path="/users" element={<UserOrders />} />
        <Route path="*" element={<Navigate to="/users" replace />} />
      </Routes>
    </ErrorBoundary>
  );
}

export default App;
