// libs/users-vue/ui/src/lib/user-total-orders/user-total-orders.vue
<script setup lang="ts">
interface UserTotalOrdersProps {
  totalAmount: number;
}

defineProps<UserTotalOrdersProps>();
</script>

<template>
  <div class="card">
    <span class="label">Total orders</span>
    <strong class="value">${{ totalAmount.toFixed(2) }}</strong>
  </div>
</template>

<style scoped>
.card {
  padding: 1rem;
  border: 1px solid #d8dbe2;
  border-radius: 12px;
  background: #fff;
}
.label {
  display: block;
  margin-bottom: 0.35rem;
  font-size: 0.85rem;
  color: #667085;
}
.value {
  font-size: 1.1rem;
}
</style>

// libs/users-react/ui/src/lib/user-total-orders/user-total-orders.tsx
import { memo } from 'react';
import type { CSSProperties } from 'react';

interface UserTotalOrdersProps {
  totalAmount: number;
}

export const UserTotalOrders = memo(function UserTotalOrders({ totalAmount }: UserTotalOrdersProps) {
  return (
    <div style={cardStyle}>
      <span style={labelStyle}>Total orders</span>
      <strong style={valueStyle}>${totalAmount.toFixed(2)}</strong>
    </div>
  );
});

const cardStyle: CSSProperties = {
  padding: '1rem',
  border: '1px solid #d8dbe2',
  borderRadius: 12,
  background: '#fff',
};

const labelStyle: CSSProperties = {
  display: 'block',
  marginBottom: '0.35rem',
  fontSize: '0.85rem',
  color: '#667085',
};

const valueStyle: CSSProperties = { fontSize: '1.1rem' };
